[project]
name = "advent-2025"
version = "0.1.0"
description = "Solutions to Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]
